version: '3'

services:
  db:
    image: mysql:5.7
    container_name: django_mysql
    environment:
        MYSQL_ROOT_PASSWORD: "HelloDude"
        MYSQL_DATABASE: "instawork"
    volumes:
        - mysql_data:/var/lib/mysql
    restart: always
    ports:
        - "33060:3306"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
volumes:
  mysql_data:
